[platformio]
default_envs = HMI ; Placa padrão para compilar
; Importa as configurações dos outros arquivos .ini:
extra_configs =
    boards_config/cyd.ini
    boards_config/t_hmi.ini
    boards_config/cardputer.ini

[env]
platform = espressif32@6.7.0
framework = arduino
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ 7.1.0
    mathieucarbou/ESPAsyncWebServer @ 3.1.5
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/sapteinkabeltann/lua511-esp32

build_flags =
    -D KRYONOS_VERSION=\"2.0.0\"
    -D KRYONOS_API_LEVEL=2

    -D USER_SETUP_LOADED=1

    -D DISP_HOR_RES=240
    -D DISP_VER_RES=320

    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1

    -Ilib/wren/src/include
    -Ilib/wren/src/vm
    -Ilib/wren/src/optional