const char HARIX_WREN_API_SOURCE[] =
    "class Harix {\n"
    "    foreign static millis()\n"
    "    foreign static micros()\n"
    "    foreign static delay(time)\n"
    "    foreign static delayMicroseconds(time)\n"
    "    foreign static print(value)\n"
    "    foreign static getInfo()\n"
    "    foreign static restart()\n"
    "    foreign static getTemperature()\n"
    "    foreign static hasTemperatureSensor()\n"
    "    foreign static getTime()\n"
    "    foreign static getSeconds()\n"
    "    foreign static getDate()\n"
    "    foreign static getYear()\n"
    "    foreign static getMonth()\n"
    "    foreign static getDay()\n"
    "    foreign static getTimezone()\n"
    "    foreign static getOSVersion()\n"
    "    foreign static getAPILevel()\n"
    "}\n"

    "\n"
    "class Display {\n"
    "    foreign static fillScreen(color)\n"
    "    foreign static fillRect(x, y, width, height, color)\n"
    "    foreign static drawRect(x, y, width, height, color)\n"
    "    foreign static drawLine(x0, y0, x1, y1, color)\n"
    "    foreign static drawPixel(x, y, color)\n"
    "    foreign static drawCircle(x, y, radius, color)\n"
    "    foreign static fillCircle(x, y, radius, color)\n"
    "    foreign static drawTriangle(x0, y0, x1, y1, x2, y2, color)\n"
    "    foreign static fillTriangle(x0, y0, x1, y1, x2, y2, color)\n"
    "    foreign static drawRoundRect(x, y, width, height, radius, color)\n"
    "    foreign static fillRoundRect(x, y, width, height, radius, color)\n"
    "    foreign static drawBMP(path, x, y)\n"
    "    foreign static drawString(text, x, y, font)\n"
    "    foreign static setTextColor(foreground, background)\n"
    "    foreign static setTextSize(size)\n"
    "    foreign static color(red, green, blue)\n"
    "    foreign static screenWidth()\n"
    "    foreign static screenHeight()\n"
    "}\n"

    "\n"
    "class Sprite {\n"
    "    foreign static create(width, height)\n"
    "    foreign static delete()\n"
    "    foreign static push(x, y)\n"
    "    foreign static bind(enabled)\n"
    "    foreign static drawFastVLine(x, y, height, color)\n"
    "    foreign static drawFastHLine(x, y, width, color)\n"
    "}\n"
    "\n"

     "class GPIO {\n"
    "    foreign static pinMode(pin, mode)\n"
    "    foreign static digitalWrite(pin, value)\n"
    "    foreign static digitalRead(pin)\n"
    "    foreign static analogRead(pin)\n"
    "    foreign static analogWrite(pin, value)\n"
    "    foreign static pulseIn(pin, state, timeout)\n"
    "}\n"
    "\n"

    "class Input {\n"
    "    foreign static getKey()\n"
    "    foreign static isKeyPressed(key)\n"
    "    foreign static getKeyInput()\n"
    "    foreign static getChar()\n"
    "    foreign static getTouch()\n"
    "}\n"

    "class Network {\n"
    "    foreign static getIPAddress()\n"
    "    foreign static isWiFiActive()\n"
    "}\n"
    "\n"

    "class FileSystem {\n"
    "    foreign static readTextFile(path)\n"
    "    foreign static writeTextFile(path, content)\n"
    "    foreign static deleteFile(path)\n"
    "    foreign static fileExists(path)\n"
    "    foreign static listDir(path)\n"
    "    foreign static appendTextFile(path, content)\n"
    "    foreign static renameFile(pathFrom, pathTo)\n"
    "    foreign static mkdir(path)\n"
    "    foreign static rmdir(path)\n"
    "    foreign static isDirectory(path)\n"
    "    foreign static isFile(path)\n"
    "    foreign static getFileSize(path)\n"
    "    foreign static getTotalSpace(drive)\n"
    "    foreign static getUsedSpace(drive)\n"
    "    foreign static getFreeSpace(drive)\n"
    "    foreign static getFileMD5(path)\n"
    "    foreign static mountSD()\n"
    "    foreign static unmountSD()\n"
    "}\n"
    "\n"

    "class Keyboard {\n"
    "    foreign static prompt(message, initialText)\n"
    "}\n";