; =========================================================================
; AMBIENTE: M5Stack Cardputer v1.1
; Stamp-S3A + ST7789V2 240x135
; =========================================================================

[env:Cardputer]

platform = espressif32@6.7.0
board = m5stack-stamps3
framework = arduino
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions_cardputer.csv

build_type = debug

lib_deps =
    ${env.lib_deps}

build_src_filter =
    +<*>
    -<boards/>
    +<boards/cardputer/>

build_flags =
    ${env.build_flags}

    ; -------------------------------------------------------------
    ; TARGET
    ; -------------------------------------------------------------

    -D TARGET_CARDPUTER=1
    -D ESP32S3=1

    ; -------------------------------------------------------------
    ; USB
    ; -------------------------------------------------------------

    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

    ; -------------------------------------------------------------
    ; DISPLAY
    ; -------------------------------------------------------------

    -D DISP_HOR_RES=135
    -D DISP_VER_RES=240

    ; -------------------------------------------------------------
    ; TFT_eSPI
    ; -------------------------------------------------------------

    -D ST7789_2_DRIVER=1
    -D CGRAM_OFFSET=1
    -D TFT_RGB_ORDER=TFT_RGB
    -D USE_HSPI_PORT=1

    -D TFT_WIDTH=135
    -D TFT_HEIGHT=240

    ; -------------------------------------------------------------
    ; ST7789V2
    ; Cardputer v1.1
    ; -------------------------------------------------------------

    -D TFT_MOSI=35
    -D TFT_SCLK=36
    -D TFT_DC=34
    -D TFT_RST=33
    -D TFT_CS=37
    -D TFT_BACKLIGHT_ON=HIGH

    ; -------------------------------------------------------------
    ; BACKLIGHT
    ; -------------------------------------------------------------

    -D TFT_BL=38

    -D SPI_FREQUENCY=27000000
    -D SPI_READ_FREQUENCY=20000000