; =========================================================================
; AMBIENTE: CYD (Cheap Yellow Display / ESP32 + ILI9341/ST7789)
; =========================================================================
[env:CYD]
board = esp32dev
build_src_filter = +<*> -<boards/> +<boards/cyd/>

lib_deps =
    ${env.lib_deps}
    https://github.com/PaulStoffregen/XPT2046_Touchscreen@^1.4.0

build_flags =
    ${env.build_flags}
    -D TARGET_CYD=1

    -D ENABLE_MEM_OVERLAY=1

    ; --- Configuração do Display (TFT_eSPI) ---
    -D ILI9341_2_DRIVER=1
    -D TFT_RGB_ORDER=TFT_RGB
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D SPI_FREQUENCY=55000000

    ; --- Pinos do Touch Resistivo (XPT2046) ---
    -D USE_HSPI_PORT=1
    -D TOUCHSCREEN_SCLK_PIN=25
    -D TOUCHSCREEN_MISO_PIN=39
    -D TOUCHSCREEN_MOSI_PIN=32
    -D TOUCHSCREEN_CS_PIN=33
    -D TOUCHSCREEN_IRQ_PIN=36

    ; --- Pinos de Cartão SD (HSPI) ---
    -D SD_MISO_PIN=19
    -D SD_MOSI_PIN=23
    -D SD_SCLK_PIN=18
    -D SD_CS_PIN=5