; =========================================================================
; AMBIENTE: CYD (Cheap Yellow Display / ESP32 + ILI9341/ST7789)
; =========================================================================
[env:CYD]
board = esp32dev
build_src_filter = +<*> -<boards/> +<boards/cyd/>
board_build.partitions = no_ota.csv

lib_deps =
    ${env.lib_deps}
    nitek/XPT2046_Bitbang_Slim@^2.0.0

build_flags =
    ${env.build_flags}
    -D TARGET_CYD=1

    -D ENABLE_MEM_OVERLAY=1

    ; --- Configuração do Display (TFT_eSPI) ---
    -D ILI9341_2_DRIVER=1
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D SPI_FREQUENCY=55000000

    ; --- Pinos do Touch Resistivo (XPT2046) ---
    -D USE_HSPI_PORT=1